"""Add location fields to Locales

Revision ID: cd3694a7a1ef
Revises: dd795f58eb30
Create Date: 2025-11-06 18:35:00.489032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3694a7a1ef'
down_revision = 'dd795f58eb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('ciudad')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
